### ISSUE TITLE
Failed to build admin plugin

### ISSUE THREAD

**Issue by ShinZ6** [Red5/red5-plugins#14]
The following error ocurred when try to build while following the guide:

Failed to execute goal on project authplugin: Could not resolve dependencies for project org.red5:authplugin:jar:1.0.8-M1: Failure to find org.red5:red5-server:jar:1.0.2-RC3 in http://red5.googlecode.com/svn/repository was cached in the local repository, resolution will not be reattempted until the update interval of Red5 has elapsed or updates are forced -> [Help 1]

**Comment by viaricardo** [comment]
Same problem here :(

**Comment by mondain** [comment]
The admin plugin is not being maintained at this time; if you want to update the poms to the latest versions and create a PR, I'll take a look at it.
