### ISSUE TITLE
Plugins fail to compile

### ISSUE THREAD

**Issue by nightstryke** [Red5/red5-plugins#16]
I've downloaded all the plugins, but they fail to compile, all are still referencing the code.google.com repositories and googlecode.com repositories which are no longer available as google shut down code last year. Would be great if someone fixed the pom.xml to use the current github because without it the plugins fail to compile no matter what I do.

**Comment by mondain** [comment]
Which plugins? If you would like, you can compare non-working plugins with the tomcat plugin or websocket plugin to determine the newer entries.

**Comment by MikeMannox** [comment]
Having the same issue, 

I checked out the projects, followed the directions as listed from _Build from source_ in the ReadMe and get the following errors:

When building from ./red5-plugins root:
```bash
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /home/jenkins/Projects/StreamingServer/red5-plugins/tomcat/target/classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.002 s]
[INFO] tomcatplugin ....................................... FAILURE [  7.685 s]
[INFO] mqttplugin ......................................... SKIPPED
[INFO] securityplugin ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.690 s
[INFO] Finished at: 2017-09-05T12:14:03+01:00
[INFO] Final Memory: 26M/369M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project tomcatplugin: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tomcatplugin
```
yet:
```
javac -version
The program 'javac' can be found in the following packages:
 * default-jdk
 * ecj
 * gcj-5-jdk
 * openjdk-8-jdk-headless
 * gcj-4.8-jdk
 * gcj-4.9-jdk
 * openjdk-9-jdk-headless
```

and for building from ./red5-plugins/rtspplugin:
```bash
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.346 s
[INFO] Finished at: 2017-09-05T12:16:11+01:00
[INFO] Final Memory: 16M/288M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project authplugin: Could not resolve dependencies for project org.red5:authplugin:jar:1.0.8-M1: The following artifacts could not be resolved: org.springframework:spring-asm:jar:4.2.6.RELEASE, org.red5:red5-io:jar:1.0.2, org.red5:red5-server:jar:1.0.2-RC3: Could not find artifact org.springframework:spring-asm:jar:4.2.6.RELEASE in Red5 (http://red5.googlecode.com/svn/repository) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Would it not be possible to have plugins available to download from `releases` ?

**Comment by MikeMannox** [comment]
Hi, 

I am experiencing the same issue, see:

```bash
$ cd rtspplugin/
$ mvn -Dmaven.test.skip=true package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Red5 :: authplugin 1.0.8-M1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.springframework:spring-asm:jar:4.2.6.RELEASE is missing, no dependency information available
[WARNING] The POM for org.red5:red5-io:jar:1.0.2 is missing, no dependency information available
[WARNING] The POM for org.red5:red5-server:jar:1.0.2-RC3 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.826 s
[INFO] Finished at: 2017-09-05T13:09:00+01:00
[INFO] Final Memory: 12M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project authplugin: Could not resolve dependencies for project org.red5:authplugin:jar:1.0.8-M1: The following artifacts could not be resolved: org.springframework:spring-asm:jar:4.2.6.RELEASE, org.red5:red5-io:jar:1.0.2, org.red5:red5-server:jar:1.0.2-RC3: Failure to find org.springframework:spring-asm:jar:4.2.6.RELEASE in http://red5.googlecode.com/svn/repository was cached in the local repository, resolution will not be reattempted until the update interval of Red5 has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by MikeMannox** [comment]
Is this project dead?

Could one of the project owners please help/respond?

**Comment by mondain** [comment]
Plugins built this morning just as expected: ```[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tomcatplugin ....................................... SUCCESS [  9.060 s]
[INFO] mqttplugin ......................................... SUCCESS [  4.871 s]
[INFO] securityplugin ..................................... SUCCESS [  2.957 s]
[INFO] parent ............................................. SUCCESS [  0.138 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.077 s
[INFO] Finished at: 2017-09-09T14:46:18-07:00
[INFO] Final Memory: 35M/435M
```

**Comment by MikeMannox** [comment]
I am after, `RSTP` and it doesn't appear in that list. 

Would it be possible to make these available under releases, please?

**Comment by nightstryke** [comment]
Yeah those that you listed come pre-packaged with Red5 But aside from the rest in the Red5 Plugins part of github none of these compile!

adminplugin
authplugin
cluster
definst
example
icyplugin
jetty
mpeg-ts
oflademoplugin
policyserver
rtspplugin
securityplugin
undertow
winstone

**Comment by mondain** [comment]
You have to at least have a working build environment first; that `javac` issue is the first thing to resolve locally. The projects / modules you listed are not in the modules list because they aren't being supported; which doesn't mean that they won't work, just that no-one is working on them. Which module specifically did you want?

**Comment by mondain** [comment]
The plugins which have been built and deployed are available for download at Maven Central; here is the search url http://mvnrepository.com/search?q=org.red5

**Comment by MikeMannox** [comment]
For me I am interested in RTSP & RTMP for use with Android / iOS (eventually) clients.

**Comment by nightstryke** [comment]
I'd personally like the Admin and RTSP plugins updated.

**Comment by mondain** [comment]
The `rtspplugin` was never completed, so unfortunately that one would be a problem. The `adminplugin` is a possibility, but I'd have to take a look.

**Comment by mondain** [comment]
I don't personally have time to support or finish the development of the extra plugins; I would be glad to process any PR's submitted by interested parties.
