### ISSUE TITLE
RtpPackage and Rtcppackage

### ISSUE THREAD

**Issue by 451482030** [Red5/red5-plugins#18]
Hello, Nice to meet you. I'm studying Red5, too.  RtpPackage and Rtcppackage, Are that right?  I need Rtp and Rtcp to do something. RTP details are not found on the Internet.

**Comment by 451482030** [comment]
I just want to make sure the RTP and Rtcp in Baotou is correct

**Comment by mondain** [comment]
I am not familiar with `Baotou` and the rtp/rtsp plugin is an example that was not completed. If you need Red5 with RTP/RTCP or event WebRTC, I suggest looking into [Red5 Pro](http://red5pro.com) (it is the commercial version)
