### ISSUE TITLE
Excuse me,securityplugin support red5 1.07？

### ISSUE THREAD

**Issue by fmpoffice** [Red5/red5-plugins#9]
1、I compiled securityplugin but I don't know how to configure the red5 1.07, give advice or comments, please?

2、I've tried Customstreamer_domaincontrol_deployable_0. 8 _final this demo, but it can't run successfully
http://flashvisions.com/ready-to-use-%E2%80%93-red5-streamer-with-stream-security/
`<bean class="org.red5.core.security.PublishSecurity" init-method="init" id="publishSecurity">
<property name="application" ref="web.handler" />
<property name="htmlDomains" value="/WEB-INF/allowedHTMLdomains.txt" />
<property name="swfDomains" value="/WEB-INF/allowedSWFdomains.txt" />
<property name="publishNames" value="/WEB-INF/allowedPublishNames.txt" />
<property name="enablePublish" value="true" />
</bean> - See more at: http://flashvisions.com/ready-to-use-%E2%80%93-red5-streamer-with-stream-security/#sthash.WbOOSOpv.dpuf`
![1](https://cloud.githubusercontent.com/assets/11001031/15472445/c3dcb7f8-212d-11e6-924e-c976767c3b25.png)

**Comment by mondain** [comment]
We lack the resources to support older versions, sorry.
